#!/usr/bin/env python3
"""
envmerge - Combine .env snippets into output files with auto-inheritance.

Config format (env-config.json):
  - String value = snippet definition (alias: filename)
  - Array value = output file (filename: [aliases])
  - Dot notation enables auto-inheritance (host.dev -> host, host.dev)
"""

import argparse
import json
import shutil
from datetime import datetime
from pathlib import Path


def load_config(config_path: Path) -> tuple[dict[str, str], dict[str, list[str]]]:
    """Load config, return (snippets, outputs)."""
    with open(config_path) as f:
        config = json.load(f)
    snippets = {k: v for k, v in config.items() if isinstance(v, str)}
    outputs = {k: v for k, v in config.items() if isinstance(v, list)}
    return snippets, outputs


def resolve_inheritance(alias: str, snippets: dict[str, str]) -> list[str]:
    """Expand alias to include parent aliases via dot notation."""
    parts = alias.split(".")
    chain = []
    for i in range(1, len(parts) + 1):
        parent = ".".join(parts[:i])
        if parent in snippets:
            chain.append(parent)
    return chain


def parse_env(content: str) -> dict[str, str]:
    """Parse .env content into key-value dict."""
    result = {}
    for line in content.splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, value = line.partition("=")
            result[key.strip()] = value.strip()
    return result


def backup_if_exists(output_path: Path, history_dir: Path) -> None:
    """Backup existing output file to history directory."""
    if output_path.exists():
        history_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        backup_name = f"{timestamp}_{output_path.name}"
        shutil.copy(output_path, history_dir / backup_name)


def generate_output(
    output_name: str,
    aliases: list[str],
    snippets: dict[str, str],
    source_dir: Path,
    output_dir: Path,
    history_dir: Path,
    dry_run: bool = False,
) -> str:
    """Generate a single output file from aliases."""
    # Expand all aliases with inheritance
    expanded = []
    seen = set()
    for alias in aliases:
        for resolved in resolve_inheritance(alias, snippets):
            if resolved not in seen:
                expanded.append(resolved)
                seen.add(resolved)

    # Merge env files in order
    merged = {}
    source_files = []
    for alias in expanded:
        filename = snippets[alias]
        filepath = source_dir / filename
        if filepath.exists():
            source_files.append(filename)
            content = filepath.read_text()
            merged.update(parse_env(content))
        else:
            print(f"Warning: {filepath} not found for alias '{alias}'")

    # Build output content
    header = f"# Generated by envmerge\n# Sources: {' -> '.join(source_files)}\n\n"
    body = "\n".join(f"{k}={v}" for k, v in merged.items())
    output_content = header + body + "\n"

    if dry_run:
        print(f"=== {output_name} ===")
        print(output_content)
    else:
        output_path = output_dir / output_name
        backup_if_exists(output_path, history_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path.write_text(output_content)
        print(f"Generated: {output_path}")

    return output_content


def get_parent_vars(prefix: str, snippets: dict[str, str], source_dir: Path) -> set[str]:
    """Get all variable names from parent prefixes."""
    parent_vars = set()
    parts = prefix.split(".")
    for i in range(1, len(parts) + 1):
        parent = ".".join(parts[:i])
        if parent in snippets:
            filepath = source_dir / snippets[parent]
            if filepath.exists():
                parent_vars.update(parse_env(filepath.read_text()).keys())
    return parent_vars


def import_env(
    import_path: Path,
    prefix: str,
    config_path: Path,
    source_dir: Path,
) -> None:
    """Import an env file as a new snippet, removing inherited vars."""
    # Load current config
    with open(config_path) as f:
        config = json.load(f)
    snippets = {k: v for k, v in config.items() if isinstance(v, str)}

    # Determine alias name
    if prefix in snippets:
        # Prefix exists, use prefix.basename
        basename = import_path.stem  # filename without extension
        alias = f"{prefix}.{basename}"
    else:
        alias = prefix

    # Get vars from parent prefixes to exclude
    parent_vars = get_parent_vars(prefix, snippets, source_dir)

    # Parse import file and remove inherited vars
    import_content = import_path.read_text()
    import_vars = parse_env(import_content)
    unique_vars = {k: v for k, v in import_vars.items() if k not in parent_vars}

    # Create new snippet file
    new_filename = f"{alias.replace('.', '_')}.env"
    new_filepath = source_dir / new_filename
    source_dir.mkdir(parents=True, exist_ok=True)

    # Write snippet with only unique vars
    lines = [f"# Imported from {import_path.name}", f"# Alias: {alias}", ""]
    lines.extend(f"{k}={v}" for k, v in unique_vars.items())
    new_filepath.write_text("\n".join(lines) + "\n")

    # Update config
    config[alias] = new_filename
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2)
        f.write("\n")

    removed_count = len(import_vars) - len(unique_vars)
    print(f"Imported: {import_path} -> {alias}")
    print(f"  Created: {new_filepath}")
    print(f"  Variables: {len(unique_vars)} kept, {removed_count} removed (inherited)")


def main():
    parser = argparse.ArgumentParser(description="Merge .env snippets into output files")
    parser.add_argument("-c", "--config", default="env-config.json", help="Config file path")
    parser.add_argument("-o", "--output", help="Generate specific output only")
    parser.add_argument("--dry-run", action="store_true", help="Print output without writing")
    parser.add_argument("--import", dest="import_file", metavar="FILE", help="Import env file")
    parser.add_argument("--prefix", help="Prefix for imported file (required with --import)")
    args = parser.parse_args()

    config_path = Path(args.config)
    base_dir = config_path.parent
    source_dir = base_dir / "source"
    output_dir = base_dir / "output"
    history_dir = base_dir / "history"

    # Handle import mode
    if args.import_file:
        if not args.prefix:
            print("Error: --prefix is required when using --import")
            return 1
        import_env(Path(args.import_file), args.prefix, config_path, source_dir)
        return 0

    snippets, outputs = load_config(config_path)

    if args.output:
        if args.output not in outputs:
            print(f"Error: '{args.output}' not found in config outputs")
            return 1
        outputs = {args.output: outputs[args.output]}

    for output_name, aliases in outputs.items():
        generate_output(
            output_name, aliases, snippets, source_dir, output_dir, history_dir, args.dry_run
        )

    return 0


if __name__ == "__main__":
    exit(main())
